export class ZwiftyFiftyRacesTemplate {
  route: string = '';
  world: string = '';
  linkRoute: string = '';
  laps: string = '';
  length: string = '';
  hm: string = '';
  climbs: string[] = [];
  sprints: string[] = [];
  sprintLaps: string[] = [];
  bonus: string[] = [];
      
  constructor(initializer?: any) {
    if (!initializer) return;
    if (initializer.route) this.route = initializer.route;
    if (initializer.world) this.world = initializer.world;
    if (initializer.linkRoute) this.linkRoute = initializer.linkRoute;
    if (initializer.laps) this.laps = initializer.laps;
    if (initializer.length) this.length = initializer.length;
    if (initializer.hm) this.hm = initializer.hm;
    if (initializer.climbs) this.climbs = initializer.climbs;
    if (initializer.sprints) this.sprints = initializer.sprints;
    if (initializer.sprintLaps) this.sprintLaps = initializer.sprintLaps;
    if (initializer.bonus) this.bonus = initializer.bonus;
  }
}

export const ZwiftyFiftyRacesData = [
  new ZwiftyFiftyRacesTemplate({
    route: 'The London Pretzel',
    world: 'London',
    linkRoute: 'https://zwiftinsider.com/route/the-london-pretzel/',
    laps: '1',
    length: '55.6',
    hm: '531',
    climbs: ['Fox Hill', 'Box Hill'],
    sprints: ['Fox Hill','Box Hill'],
    sprintLaps: ['1','1'],
    bonus: ['3.0','2.0','1.0'],
  }),
  new ZwiftyFiftyRacesTemplate({
    route: 'The Muckle Yin',
    world: 'Scotland',
    linkRoute: 'https://zwiftinsider.com/route/the-muckle-yin/',
    laps: '2',
    length: '47',
    hm: '564',    
    climbs: ['Sgurr Summit North','Sgurr Summit South'],
    sprints: ['Sgurr Summit North','Sgurr Summit South'],
    sprintLaps: ['1,2','1,2'],
    bonus: ['1.5','1.0','0.5'],
  }),
  new ZwiftyFiftyRacesTemplate({
    route: '2022 Bambino Fondo',
    world: 'Watopia',
    linkRoute: 'https://zwiftinsider.com/route/2022-bambino-fondo/',
    laps: '1',
    length: '52.3',
    hm: '400',  
    climbs: ['Epic KOM Bypass','Volcano KOM'],
    sprints: ['Watopia Sprint Forward','Fuego Flats Long','Fuego Flats Short','Volcano Circuit Reverse'],
    sprintLaps: ['1','1','1','1'],
    bonus: ['1.5','1.0','0.5'],
  }),
  new ZwiftyFiftyRacesTemplate({
    route: 'Downtown Titans',
    world: 'Watopia',
    linkRoute: 'https://zwiftinsider.com/route/downtown-titans/',
    laps: '2',
    length: '50.09',
    hm: '584',  
    climbs: ['Titans Groove KOM Reverse','Zwift KOM'],
    sprints: ['Titans Groove KOM Reverse','Zwift KOM'],
    sprintLaps: ['1,2','1,2'],
    bonus: ['3.0','2.0','1.0'],
  }),
  new ZwiftyFiftyRacesTemplate({
    route: 'Turf N Surf',
    world: 'Makuri Islands',
    linkRoute: 'https://zwiftinsider.com/route/turf-n-surf/',
    laps: '2',
    length: '49.3',
    hm: '394',  
    climbs: ['Turf N Surf'],
    sprints: ['Shisa Sprint Reverse'],
    sprintLaps: ['1,2'],
    bonus: ['3.0','2.0','1.0'],
  }),
  new ZwiftyFiftyRacesTemplate({
    route: '2015 UCI Worlds Course',
    world: 'Richmond',
    linkRoute: 'https://zwiftinsider.com/route/richmond-uci-worlds/',
    laps: '3',
    length: '49',
    hm: '476',  
    climbs: ['Libby 23rd Governor'],
    sprints: ['Broad St'],
    sprintLaps: ['1,2,3'],
    bonus: ['3.0','2.0','1.0'],
  }),
  new ZwiftyFiftyRacesTemplate({
    route: 'Roule Ma Poule',
    world: 'France',
    linkRoute: 'https://zwiftinsider.com/route/roule-ma-poule/',
    laps: '2',
    length: '50.09',
    hm: '418',
    climbs: ['Petit KOM Reverse'],
    sprints: ['Pavé Sprint','Marina Sprint'],
    sprintLaps: ['1,2','1,2'],
    bonus: ['1.5','1.0','0.5'],
  }),
  new ZwiftyFiftyRacesTemplate({
    route: 'Island Hopper',
    world: 'Makuri Islands',
    linkRoute: 'https://zwiftinsider.com/route/island-hopper/',
    laps: '3',
    length: '54.1',
    hm: '387',
    climbs: ['Shisa Sprint Hill'],
    sprints: ['Shisa Sprint'],
    sprintLaps: ['1,2,3'],
    bonus: ['3.0','2.0','1.0'],
  }),
  new ZwiftyFiftyRacesTemplate({
    route: 'RGV',
    world: 'France',
    linkRoute: 'https://zwiftinsider.com/route/rgv/',
    laps: '2',
    length: '49.8',
    hm: '267',
    climbs: [],
    sprints: ['Aqueduc KOM Reverse','Ballon Sprint Reverse'],
    sprintLaps: ['1,2','1,2'],
    bonus: ['3.0','2.0','1.0'],
  }),
  new ZwiftyFiftyRacesTemplate({
    route: 'Innsbruckring',
    world: 'Innsbruck',
    linkRoute: 'https://zwiftinsider.com/route/innsbruckring/',
    laps: '6',
    length: '53',
    hm: '463',
    climbs: ['Leg Snapper KOM'],
    sprints: ['Leg Snapper KOM'],
    sprintLaps: ['1,2,3,4,5,6'],
    bonus: ['1.5','1.0','0.5'],
  }),
  new ZwiftyFiftyRacesTemplate({
    route: 'Spiral Into The Volcano',
    world: 'Watopia',
    linkRoute: 'https://zwiftinsider.com/route/spiral-into-the-volcano/',
    laps: '1',
    length: '55.8',
    hm: '355',
    climbs: ['Volcano KOM'],
    sprints: ['Fuego Flats','Watopia Sprint'],
    sprintLaps: ['1','1'],
    bonus: ['6','4','2'],
  }),
  new ZwiftyFiftyRacesTemplate({
    route: 'Sukis Playground',
    world: 'Makuri Islands',
    linkRoute: 'https://zwiftinsider.com/route/sukis-playground/',
    laps: '3',
    length: '55.1',
    hm: '450',
    climbs: ['Sukis Playground'],
    sprints: ['Country Sprint'],
    sprintLaps: ['1,2,3'],
    bonus: ['3','2','1'],
  }),
  new ZwiftyFiftyRacesTemplate({
    route: 'Bambino Fondo',
    world: 'Watopia',
    linkRoute: 'https://zwiftinsider.com/route/bambino-fondo/',
    laps: '1',
    length: '52.4',
    hm: '580',
    climbs: ['Zwift KOM','Epic KOM start to Windmills','Jungle Banner to Windmills','Volcano KOM'],
    sprints: ['JWB Sprint'],
    sprintLaps: ['1,2'],
    bonus: ['6','4','2'],
  }),
  new ZwiftyFiftyRacesTemplate({
    route: '2022 Cycling Esports World Championships Route',
    world: 'New York',
    linkRoute: 'https://zwiftinsider.com/route/2022-cycling-esports-world-championships-route/',
    laps: '1',
    length: '55',
    hm: '943',
    climbs: ['NY KOM'],
    sprints: ['NY Sprint'],
    sprintLaps: ['1,2,3'],
    bonus: ['4','2','1'],
  }),
  new ZwiftyFiftyRacesTemplate({
    route: 'Snowman',
    world: 'Watopia',
    linkRoute: 'https://zwiftinsider.com/route/snowman/',
    laps: '1',
    length: '44.2',
    hm: '579',
    climbs: ['Mayan Itza The Grade Final Part'],
    sprints: ['Mayan Mountainside KOM','Itza KOM'],
    sprintLaps: ['1','1'],
    bonus: ['3','2','1'],
  }),
  new ZwiftyFiftyRacesTemplate({
    route: 'Itza Party',
    world: 'Watopia',
    linkRoute: 'https://zwiftinsider.com/route/itza-party/',
    laps: '1',
    length: '45.7',
    hm: '506',
    climbs: ['Zwift KOM','Titans Groove KOM Reverse','Mayan Mountainside KOM Itza KOM'],
    sprints: ['Woodland Sprint Reverse','Sasquatch Sprint Reverse','Acropolis Sprint Reverse'],
    sprintLaps: ['1','1','1'],
    bonus: ['3','2','1'],
  }),
  new ZwiftyFiftyRacesTemplate({
    route: 'Greater London 8',
    world: 'London',
    linkRoute: 'https://zwiftinsider.com/route/greater-london-8/',
    laps: '2',
    length: '48.1',
    hm: '556',
    climbs: ['Box Hill'],
    sprints: ['Box Hill'],
    sprintLaps: ['1,2'],
    bonus: ['3','2','1'],
  }),
  new ZwiftyFiftyRacesTemplate({
    route: 'Makuri Pretzel',
    world: 'Makuri Islands',
    linkRoute: 'https://zwiftinsider.com/route/makuri-pretzel/',
    laps: '1',
    length: '48.1',
    hm: '556',
    climbs: [],
    sprints: ['Shisa Sprint Reverse','Shisa Sprint'],
    sprintLaps: ['1','1'],
    bonus: ['3','2','1'],
  }),
  new ZwiftyFiftyRacesTemplate({
    route: 'Deca Dash',
    world: 'Watopia',
    linkRoute: 'https://zwiftinsider.com/route/deca-dash/',
    laps: '1',
    length: '52.6',
    hm: '500',
    climbs: ['Jarvis KOM Reverse'],
    sprints: [],
    sprintLaps: [],
    bonus: [],
  }),
  new ZwiftyFiftyRacesTemplate({
    route: 'Mighty Metropolitan',
    world: 'New York',
    linkRoute: 'https://zwiftinsider.com/route/mighty-metropolitan/',
    laps: '2',
    length: '40.6',
    hm: '639',
    climbs: ['New York KOM Reverse'],
    sprints: ['New York KOM Reverse'],
    sprintLaps: ['1,2'],
    bonus: ['6','4','2'],
  }),
  new ZwiftyFiftyRacesTemplate({
    route: 'Shisa Shakedown',
    world: 'Watopia',
    linkRoute: 'https://zwiftinsider.com/route/shisa-shakedown/',
    laps: '1',
    length: '53.5',
    hm: '556',
    climbs: ['Castle KOM Temple KOM'],
    sprints: ['Railway Sprint','Castle KOM','Temple KOM'],
    sprintLaps: ['1','1','1'],
    bonus: ['3','2','1'],
  }),
  new ZwiftyFiftyRacesTemplate({
    route: 'Navig8',
    world: 'Watopia',
    linkRoute: 'https://zwiftinsider.com/route/navig8/',
    laps: '1',
    length: '66.1',
    hm: '423',
    climbs: ['Mayan Mountainside KOM Itza KOM'],
    sprints: ['Mayan Mountainside KOM','Itza KOM'],
    sprintLaps: ['1','1'],
    bonus: ['6','4','2'],
  }),
  new ZwiftyFiftyRacesTemplate({
    route: 'Big Foot Hills',
    world: 'Watopia',
    linkRoute: 'https://zwiftinsider.com/route/big-foot-hills/',
    laps: '1',
    length: '69.9',
    hm: '714',
    climbs: ['Titans Groove KOM','Zwift KOM','Volcano KOM','Titans Groove KOM Reverse','Zwift KOM Reverse'],
    sprints: ['Titans Groove KOM','Zwift KOM','Volcano KOM','Titans Groove KOM Reverse','Zwift KOM Reverse'],
    sprintLaps: ['1','1','1','1','1'],
    bonus: ['3.0','2.0','1.0'],
  }),
  new ZwiftyFiftyRacesTemplate({
    route: 'Douce France',
    world: 'France',
    linkRoute: 'https://zwiftinsider.com/route/douce-france/',
    laps: '2',
    length: '48.8',
    hm: '270',
    climbs: [],
    sprints: ['Ballon Sprint','Aqueduc KOM','Pavé Sprint','Marina Sprint'],
    sprintLaps: ['1,2','1,2','1,2','1,2'],
    bonus: ['1.5','1.0','0.5'],
  }),
  new ZwiftyFiftyRacesTemplate({
    route: 'Zwift Games 2024 Epic',
    world: 'Watopia',
    linkRoute: 'https://zwiftinsider.com/route/zwift-games-2024-epic/',
    laps: '1',
    length: '81.7',
    hm: '878',
    climbs: ['Zwift KOM','Titans Groove KOM Reverse','Titans Groove KOM','Zwift KOM Reverse'],
    sprints: ['Woodland Sprint Reverse','Sasquatch Sprint Reverse','Acropolis Sprint Reverse'],
    sprintLaps: ['1','1','1'],
    bonus: ['3','2','1'],
  }),
  new ZwiftyFiftyRacesTemplate({
    route: 'Knights Of The Roundabout',
    world: 'France',
    linkRoute: 'https://zwiftinsider.com/route/knights-of-the-roundabout/',
    laps: '1',
    length: '54.4',
    hm: '359',
    climbs: ['Petit KOM'],
    sprints: ['Aqueduc KOM','Sprint du Cratère','Sprinteur Sprint','Petit KOM'],
    sprintLaps: ['1','1','2','1'],
    bonus: ['3','2','1'],
  }),
];